### ISSUE TITLE
Revenj version detection

### ISSUE THREAD

**Issue by dstimac** [ngs-doo/dsl-compiler-client#38] opened 2015-03-27 13:08 UTC
Compiling new generated model with old revenj present in compile direcotry brakes with wall of text errors containing "error CS0246: The type or namespace name `IPostgresTuple' could not be found. Are you missing an assembly reference?" messages.

Use case:
dsl-clc.jar version used : 1.2.0
Older revenj present in compile directory.
Compiler flags used: -java_client; -settings=active-record; -revenj -migration; log; download

Removing old revenj from compile folder fixes this issue but it would be nice to have warning about incompatible revenj versions.

**Comment by zapov** [comment] 2015-04-04 05:52
Duplicate of #25

**Closed by zapov** 2015-04-04 05:52 UTC
